# Generated by Django 2.0.4 on 2018-04-09 19:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('size', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('album_group_name', models.CharField(max_length=100)),
                ('order', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['quad', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='templateentry',
            name='quad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='bandbrackets.TemplateQuad'),
        ),
        migrations.AddField(
            model_name='templatebracket',
            name='bot_left_quad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_as_bot_left', to='bandbrackets.TemplateQuad'),
        ),
        migrations.AddField(
            model_name='templatebracket',
            name='bot_right_quad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_as_bot_right', to='bandbrackets.TemplateQuad'),
        ),
        migrations.AddField(
            model_name='templatebracket',
            name='top_left_quad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_as_top_left', to='bandbrackets.TemplateQuad'),
        ),
        migrations.AddField(
            model_name='templatebracket',
            name='top_right_quad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_as_top_right', to='bandbrackets.TemplateQuad'),
        ),
        migrations.AlterUniqueTogether(
            name='templateentry',
            unique_together={('quad', 'order')},
        ),
    ]
