# Generated by Django 2.0.4 on 2018-04-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandbrackets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg_color', models.IntegerField()),
                ('font_color', models.IntegerField()),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_groups', related_query_name='album_group', to='bandbrackets.TemplateBracket')),
            ],
        ),
        migrations.AlterModelOptions(
            name='templateentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='templateentry',
            unique_together=set(),
        ),
        migrations.AlterOrderWithRespectTo(
            name='templateentry',
            order_with_respect_to='quad',
        ),
    ]
