# Generated by Django 2.0.4 on 2018-04-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandbrackets', '0002_auto_20180410_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumgroup',
            options={'verbose_name': '04 Album Group', 'verbose_name_plural': '04 Album Groups'},
        ),
        migrations.AlterModelOptions(
            name='templatebracket',
            options={'verbose_name': '01 Template Bracket', 'verbose_name_plural': '01 Template Brackets'},
        ),
        migrations.AlterModelOptions(
            name='templateentry',
            options={'verbose_name': '03 Template Entry', 'verbose_name_plural': '03 Template Entries'},
        ),
        migrations.AlterModelOptions(
            name='templatequad',
            options={'verbose_name': '02 Template Quad', 'verbose_name_plural': '02 Template Quads'},
        ),
    ]
