# Generated by Django 2.0.4 on 2018-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandbrackets', '0003_auto_20180410_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebracket',
            name='size',
            field=models.SmallIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32')], default=32),
        ),
    ]
