# Generated by Django 2.0.4 on 2018-04-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandbrackets', '0004_auto_20180410_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateentry',
            name='order',
        ),
    ]
