# Generated by Django 2.0.4 on 2018-04-11 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandbrackets', '0005_remove_templateentry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatebracket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
