# Generated by Django 2.0.4 on 2018-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandbrackets', '0006_templatebracket_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebracket',
            name='size',
            field=models.SmallIntegerField(choices=[(32, '32'), (16, '16'), (8, '8'), (4, '4')], default=32),
        ),
    ]
